from KissanMart.settings import STATIC_ROOT

USER_PROFILE_PICTURES_PATH = STATIC_ROOT + "\\_UserProfiles"
PRODUCT_CATEGORY_PICTURES_PATH = STATIC_ROOT+ "\\_ProductCategory"
PRODUCT_PICTURES_PATH = STATIC_ROOT+ "\\_Products"

DB_USER_PROFILE_PICTURES_PATH = "_UserProfiles"
DB_PRODUCT_CATEGORY_PICTURES_PATH = "_ProductCategory"
DB_PRODUCT_PICTURES_PATH = "_Products"